zammad_directories:
  - dir: zammad-backup
  - dir: zammad-data
  - dir: zammad-tmp
  - dir: postgresql-data
    mode: 700
  - dir: postgresql-run
    mode: 775
  - dir: postgresql-passwd
  - dir: elasticsearch-data
  - dir: elasticsearch-config
  - dir: elasticsearch-logs
  - dir: nginx-config
  - dir: nginx-logs
  - dir: nginx-tmp

zammad_elasticsearch_files:
  - src: elasticsearch.yml
    mode: 660
  - src: log4j2.properties
    mode: 660

zammad_postgres_passwd_path: "{{ zammad_base_path }}/postgresql-passwd/passwd"
