galaxy_info:
  author: Jan Christian Grünhage
  description: deploys a containerized ktra instance
  company: Famedly GmbH

  license: AGPL-3.0-only

  min_ansible_version: "2.10"

  galaxy_tags: []

dependencies: []
