---
- name: launch redis
  become: yes
  docker_container:
    name: redis
    image: docker.io/redis:5.0.5-alpine
    command: "redis-server --appendonly yes"
    volumes:
      - /opt/redis/data:/data
    restart_policy: unless-stopped

- name: launch mariadb
  become: yes
  docker_container:
    name: mariadb
    image: docker.io/mariadb:10.4.6
    volumes:
      - /opt/mariadb/database:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{ matomo_db_password }}"
      MYSQL_DATABASE: "{{ matomo_db_name }}"
      MYSQL_USER: "{{ matomo_db_user }}"
      MYSQL_PASSWORD: "{{ matomo_db_password }}"
    restart_policy: unless-stopped

- name: launch matomo
  become: yes
  docker_container:
    name: matomo
    image: docker.io/matomo:3.13.5-apache
    pull: true
    links:
      - mariadb:mariadb
      - redis:redis
    volumes:
      - /opt/matomo/config:/var/www/html/config
      - /opt/matomo/logs:/var/www/html/logs
    labels: "{{ matomo_docker_labels }}"
    ports: "{{ matomo_docker_ports }}"
    restart_policy: unless-stopped
