dependencies: []
galaxy_info:
  author: AboveOps
  role_name: ghost
  description: Role installs Ghost blog in Docker container
  company: AboveOps
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - xenial
        - bionic
  galaxy_tags:
    - ghost
    - blog
    - publishing
    - web
    - cms
    - content
