---
galaxy_info:
  author: Jan Christian Grünhage <jan.christian@gruenhage.xyz>
  description: Deploys a containerised Dex instance
  company: Famedly GmbH

  license: AGPL-2.0-or-later
  min_ansible_version: "2.5"

  platforms:
    - name: Debian
      versions:
        - bullseye

  galaxy_tags: []
dependencies: []
