---
- name: create bitwarden directory
  file:
    state: directory
    path: "{{ bitwarden_home }}"
  become: yes

- name: deploy bitwarden
  docker_container:
    image: "{{ bitwarden_container_image }}"
    name: bitwarden
    labels: "{{ bitwarden_docker_labels_complete }}"
    env: "{{ bitwarden_env_vars }}"
    volumes:
      - "{{ bitwarden_home }}:/data"
    restart_policy: unless-stopped
  become: yes
