---
name: Ansible CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  ansible:
    uses: famedly/github-workflows/.github/workflows/ansible.yml@ansible-v1
    with:
      collection: famedly/services
