---
name: Ansible CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  ansible:
    uses: famedly/github-workflows/.github/workflows/ansible.yml@57b383862ba81dfa265bb33d492e2bbcbc96891d
    with:
      collection: famedly/services
